Repository gogoyong/pigthedice, pull requests merged in 2022-04, with the labels that each got.

#4 버튼 및 동작 과정 작성
  game.py
Labels: enhancement

#6 Creat player and computer
  player.md
Labels: question

#7 pigthedice with if,for done
  do-game
Labels: good first issue

#8 Make score board
  game.py
Labels: documentation
